# -*- coding: utf-8 -*-
"""발견물·유물 ↔ 실제 자료 대응표.

fetch.py 가 이 표를 읽어 여섯 API에서 자료를 모읍니다.
  whc   : UNESCO 세계유산 번호 (https://whc.unesco.org/en/list/<번호>)  — 설명·등재 연도·기준·나라
  wiki  : 영어 위키백과 문서 제목                                        — 요약·대표 사진(위키미디어 공용, 재사용 가능한 것만)
  gbif  : 학명 (GBIF)                                                    — 분류·흔한 이름·관찰 기록 수·자유 이용 사진
  obis  : 학명 (OBIS, 바다 생물)                                          — 바다 관찰 기록 수·깊이
  met   : 메트로폴리탄 미술관 검색어 (공공 영역 작품만)                  — 실존 소장품
  si    : 스미스소니언 오픈 액세스 검색어 (CC0만)                        — 실존 소장품
  must  : 소장품 검색 결과의 제목·문화·설명에 반드시 들어 있어야 하는 낱말(소문자, 하나라도)
  legend: 전설 속 발견 — 실제 자료는 '전설의 배경'(관련 장소·기록)으로만 쓰고 게임 설정은 살린다
번호·제목이 틀리면 fetch.py 가 이름으로 다시 찾고, 보고서(out/report.md)에 적어 둡니다.
"""

# ---------------------------------------------------------------- 발견물
DISC = {
    # 지리 (geo) — 대부분 세계유산이 아니므로 위키백과 + 가까운 세계유산
    'capegood':    dict(wiki='Cape of Good Hope', whc=1007),                 # 케이프 꽃 지역 보호구역
    'westroute':   dict(wiki='Voyages of Christopher Columbus', whc=526),    # 산토도밍고 식민 도시
    'indiaroute':  dict(wiki='Portuguese India Armadas', whc=263),           # 리스본 제로니무스 수도원·벨렘 탑
    'malacca':     dict(wiki='Strait of Malacca', whc=1223),                 # 믈라카와 조지타운
    'spiceis':     dict(wiki='Maluku Islands', gbif='Syzygium aromaticum'),
    'china':       dict(wiki='Ming dynasty', whc=1110),                      # 마카오 역사 지구
    'zipang':      dict(wiki='Iwami Ginzan Silver Mine', whc=1246),          # 은의 나라 — 이와미 은광
    'newstrait':   dict(wiki='Strait of Magellan'),
    'circum':      dict(wiki='Magellan expedition'),
    'antarctic':   dict(wiki='Antarctica', gbif='Aptenodytes forsteri'),
    'northstrait': dict(wiki='Bering Strait'),
    'endstrait':   dict(wiki='Drake Passage'),
    'australia':   dict(wiki='Australia', whc=147),                          # 카카두 국립공원
    # 자연 (nature)
    'pamukkale':   dict(whc=485, wiki='Pamukkale'),
    'huangshan':   dict(whc=547, wiki='Huangshan'),
    'uluru':       dict(whc=447, wiki='Uluru'),
    'canyon':      dict(whc=75,  wiki='Grand Canyon'),
    'monument':    dict(wiki='Monument Valley'),
    'niagara':     dict(wiki='Niagara Falls'),
    'iguazu':      dict(whc=303, wiki='Iguazu Falls'),
    # 유적 (ruin)
    'carnac':      dict(wiki='Carnac stones'),
    'stonehenge':  dict(whc=373, wiki='Stonehenge'),
    'mycenae':     dict(whc=941, wiki='Mycenae'),
    'parthenon':   dict(whc=404, wiki='Parthenon'),
    'delphi':      dict(whc=393, wiki='Delphi'),
    'knossos':     dict(whc=None, whcName='Minoan Palatial Centres', wiki='Knossos'),
    'pyramid':     dict(whc=86,  wiki='Pyramid of Djoser'),
    'giza':        dict(whc=86,  wiki='Giza pyramid complex'),
    'kings':       dict(whc=87,  wiki='Valley of the Kings'),
    'thebes':      dict(whc=87,  wiki='Karnak'),
    'abusimbel':   dict(whc=88,  wiki='Abu Simbel'),
    'troy':        dict(whc=849, wiki='Troy'),
    'ishtar':      dict(whc=278, wiki='Ishtar Gate'),
    'babel':       dict(whc=278, wiki='Etemenanki', legend=True),
    'persepolis':  dict(whc=114, wiki='Persepolis'),
    'mohenjo':     dict(whc=138, wiki='Mohenjo-daro'),
    'angkor':      dict(whc=668, wiki='Angkor Wat'),
    'yungang':     dict(whc=1039, wiki='Yungang Grottoes'),
    'qinshi':      dict(whc=441, wiki='Mausoleum of the First Qin Emperor'),
    'greatwall':   dict(whc=438, wiki='Great Wall of China'),
    'qianling':    dict(wiki='Qianling Mausoleum'),
    'muryeong':    dict(whc=1477, wiki='Tomb of King Muryeong'),
    'bulguksa':    dict(whc=736, wiki='Bulguksa'),
    'seokguram':   dict(whc=736, wiki='Seokguram'),
    'munmu':       dict(wiki='Underwater Tomb of King Munmu'),
    'hwangnyong':  dict(whc=976, wiki='Hwangnyongsa'),
    'emille':      dict(wiki='Bell of King Seongdeok'),
    'jongmyo':     dict(whc=738, wiki='Jongmyo'),
    'fertile':     dict(wiki='Tomizawa site', legend=True),
    'borobudur':   dict(whc=592, wiki='Borobudur'),
    'tula':        dict(wiki='Tula (Mesoamerican site)'),
    'nazca':       dict(whc=700, wiki='Nazca Lines'),
    'tiwanaku':    dict(whc=567, wiki='Tiwanaku'),
    'poitiers':    dict(wiki='Poitiers Cathedral'),
    'montstmichel':dict(whc=80,  wiki='Mont-Saint-Michel'),
    'stave':       dict(whc=58,  wiki='Urnes Stave Church'),
    'rusch':       dict(whc=633, wiki='Cathedral of Saint Demetrius'),
    'hagiasophia': dict(whc=356, wiki='Hagia Sophia'),
    'prester':     dict(whc=18,  wiki='Prester John', legend=True),        # 랄리벨라 암굴 교회
    'cappadocia':  dict(whc=357, wiki='Göreme'),
    'sepulchre':   dict(whc=148, wiki='Church of the Holy Sepulchre'),
    'edom':        dict(wiki='Bozrah', legend=True),
    'ur':          dict(whc=1481, wiki='Ziggurat of Ur'),
    'petra':       dict(whc=326, wiki='Petra'),
    'brendan':     dict(wiki="Saint Brendan's Island", legend=True),
    'cibola':      dict(wiki='Seven Cities of Gold', legend=True),
    'ark':         dict(wiki="Noah's Ark", legend=True),
    'djenne':      dict(whc=116, wiki='Great Mosque of Djenné'),
    'zimbabwe':    dict(whc=364, wiki='Great Zimbabwe'),
    'delhimosque': dict(wiki='Jama Masjid, Delhi'),
    'tajmahal':    dict(whc=252, wiki='Taj Mahal'),
    'qutb':        dict(whc=233, wiki='Qutb Minar'),
    'madurai':     dict(wiki='Meenakshi Temple'),
    'shwedagon':   dict(wiki='Shwedagon Pagoda'),
    'ayubuddha':   dict(whc=576, wiki='Wat Mahathat, Ayutthaya'),
    'potala':      dict(whc=707, wiki='Potala Palace'),
    'konjiki':     dict(whc=1277, wiki='Chūson-ji'),
    'pueblo':      dict(whc=353, wiki='Chaco Culture National Historical Park'),
    'machupicchu': dict(whc=274, wiki='Machu Picchu'),
    'sacsay':      dict(whc=273, wiki='Sacsayhuamán'),
    'moai':        dict(whc=715, wiki='Moai'),
    'mu':          dict(wiki='Mu (mythical lost continent)', legend=True),
    'isfahanmosque': dict(whc=115, wiki='Shah Mosque (Isfahan)'),
    'alhambra':    dict(whc=314, wiki='Alhambra'),
    'rockdome':    dict(whc=148, wiki='Dome of the Rock'),
    'ananda':      dict(whc=1588, wiki='Ananda Temple'),
    # 보물 (treasure) — 실제 유물·소장품
    'beowulf':     dict(wiki='Sutton Hoo helmet', whc=None),
    'kingjohn':    dict(wiki="King John's treasure", legend=True),
    'agamemnon':   dict(wiki='Mask of Agamemnon', whc=941),
    'tutankh':     dict(wiki='Tomb of Tutankhamun', whc=87),
    'rosetta':     dict(wiki='Rosetta Stone'),
    'sargon':      dict(wiki='Bronze Head from Nineveh'),
    'urcrown':     dict(wiki='Royal Cemetery at Ur', met='headdress Ur', must=['ur']),
    'goldplate':   dict(wiki='Apadana', whc=114),
    'ewer':        dict(wiki='Sasanian art', met='Sasanian silver ewer', must=['sasanian']),
    'shiva':       dict(wiki='Nataraja', met='Shiva Nataraja Chola bronze', must=['shiva', 'nataraja']),
    'goldelephant':dict(wiki='Wat Ratchaburana, Ayutthaya', whc=576),
    'jadesuit':    dict(wiki='Jade burial suit'),
    'bronze':      dict(wiki='Chinese ritual bronzes', met='Shang dynasty bronze ritual vessel', must=['shang']),
    'cloisonne':   dict(wiki='Cloisonné', met='cloisonne Ming dynasty', must=['ming']),
    'seismo':      dict(wiki='Houfeng Didong Yi'),
    'glassbowl':   dict(wiki='Shōsōin'),
    'goldseal':    dict(wiki='King of Na gold seal'),
    'crystalskull':dict(wiki='Crystal skull', si='crystal skull'),
    'eldorado':    dict(wiki='Muisca raft', legend=True),
    'jademask':    dict(wiki="Pakal's tomb", whc=411),                      # 팔렝케
    'grail':       dict(wiki='Holy Grail', met='Antioch Chalice', must=['chalice'], legend=True),
    'stcrown':     dict(wiki='Holy Crown of Hungary'),
    'reliquary':   dict(wiki='Shrine of the Three Kings', whc=292),         # 쾰른 대성당
    'ifehead':     dict(wiki='Ife Head'),
    # 동식물 (creature)
    'rubber':      dict(gbif='Hevea brasiliensis', wiki='Hevea brasiliensis'),
    'sequoia':     dict(gbif='Sequoiadendron giganteum', wiki='General Sherman (tree)', whc=None),
    'breadfruit':  dict(gbif='Artocarpus altilis', wiki='Breadfruit'),
    'lotus':       dict(gbif='Victoria amazonica', wiki='Victoria amazonica', whc=998),   # 중앙 아마존 보호지역
    'welwitschia': dict(gbif='Welwitschia mirabilis', wiki='Welwitschia', whc=1430),      # 나미브 모래바다
    'mangrove':    dict(gbif='Heritiera fomes', wiki='Sundarbans', whc=798),
    'papyrus':     dict(gbif='Cyperus papyrus', wiki='Cyperus papyrus'),
    'tarantula':   dict(gbif='Theraphosa blondi', wiki='Goliath birdeater'),
    'llama':       dict(gbif='Lama glama', wiki='Llama'),
    'prairiedog':  dict(gbif='Cynomys ludovicianus', wiki='Black-tailed prairie dog'),
    'moose':       dict(gbif='Alces alces', wiki='Moose'),
    'frigatebird': dict(gbif='Fregata magnificens', obis='Fregata magnificens', wiki='Magnificent frigatebird', whc=1),
    'tortoise':    dict(gbif='Chelonoidis niger', wiki='Galápagos tortoise', whc=1),
    'albatross':   dict(gbif='Diomedea exulans', obis='Diomedea exulans', wiki='Wandering albatross'),
    'kangaroo':    dict(gbif='Macropus giganteus', wiki='Eastern grey kangaroo'),
    'paradise':    dict(gbif='Paradisaea apoda', wiki='Greater bird-of-paradise'),
    'sable':       dict(gbif='Martes zibellina', wiki='Sable'),
    'tiger':       dict(gbif='Panthera tigris', wiki='Bengal tiger', whc=452),
    'panda':       dict(gbif='Ailuropoda melanoleuca', wiki='Giant panda', whc=1213),
    'porcupine':   dict(gbif='Hystrix cristata', wiki='Crested porcupine'),
    'coelacanth':  dict(gbif='Latimeria chalumnae', obis='Latimeria chalumnae', wiki='West Indian Ocean coelacanth'),
    'warthog':     dict(gbif='Phacochoerus africanus', wiki='Common warthog', whc=156),  # 세렝게티
    'komodo':      dict(gbif='Varanus komodoensis', wiki='Komodo dragon', whc=609),
    'rafflesia':   dict(gbif='Rafflesia arnoldii', wiki='Rafflesia arnoldii'),
    'carnivplant': dict(gbif='Nepenthes rajah', wiki='Nepenthes rajah', whc=1012),       # 키나발루 공원
    'startower':   dict(wiki="Tassili n'Ajjer", whc=179),
    'penguin':     dict(gbif='Spheniscus demersus', obis='Spheniscus demersus', wiki='African penguin'),
    'mandrill':    dict(gbif='Mandrillus sphinx', wiki='Mandrill'),
    'ostrich':     dict(gbif='Struthio camelus', wiki='Common ostrich'),
    'hippo':       dict(gbif='Hippopotamus amphibius', wiki='Hippopotamus'),
    'crocodile':   dict(gbif='Crocodylus niloticus', wiki='Nile crocodile', whc=801),    # 투르카나 호수
    'polarbear':   dict(gbif='Ursus maritimus', obis='Ursus maritimus', wiki='Polar bear'),
    'yeti':        dict(wiki='Yeti', whc=120, legend=True),                  # 사가르마타
    'roc':         dict(wiki='Roc (mythology)', gbif='Aepyornis maximus', legend=True),
    'mokele':      dict(wiki='Mokele-mbembe', legend=True),
    'minotaur':    dict(wiki='Minotaur', legend=True),
    'troll':       dict(wiki='Troll', legend=True),
    'nessie':      dict(wiki='Loch Ness Monster', legend=True),
    # 민족 (people)
    'khoikhoi':    dict(wiki='Khoekhoe'),
    'padaung':     dict(wiki='Kayan people (Myanmar)'),
    'cannibal':    dict(wiki='Batak', legend=True),
    'orangutan':   dict(gbif='Pongo pygmaeus', wiki='Bornean orangutan'),
    'aborigine':   dict(wiki='Aboriginal Australians', whc=147),
    'blemmyes':    dict(wiki='Blemmyes', legend=True),
    'inuit':       dict(wiki='Inuit'),
    'skraeling':   dict(wiki='Skræling', whc=4),                             # 랑스 오 메도즈
    'patagon':     dict(wiki='Tehuelche people'),
    'antpeople':   dict(legend=True),
    'nestorian':   dict(wiki='Xi\'an Stele'),
    'vampire':     dict(wiki='Vlad the Impaler', whc=902, legend=True),       # 시기쇼아라
    'aztec':       dict(wiki='Tenochtitlan', whc=412),
    'inca':        dict(wiki='Inca Empire', whc=273),
    'aurora':      dict(wiki='Aurora'),
    # 교역품 (trade) — 원산 식물·동물
    't_pepper':    dict(gbif='Piper nigrum', wiki='Black pepper'),
    't_clove':     dict(gbif='Syzygium aromaticum', wiki='Clove'),
    't_nutmeg':    dict(gbif='Myristica fragrans', wiki='Nutmeg'),
    't_cinnamon':  dict(gbif='Cinnamomum verum', wiki='Cinnamon'),
    't_ginger':    dict(gbif='Zingiber officinale', wiki='Ginger'),
    't_allspice':  dict(gbif='Pimenta dioica', wiki='Allspice'),
    't_coffee':    dict(gbif='Coffea arabica', wiki='Coffea arabica'),
    't_tea':       dict(gbif='Camellia sinensis', wiki='Camellia sinensis'),
    't_cacao':     dict(gbif='Theobroma cacao', wiki='Theobroma cacao'),
    't_tobacco':   dict(gbif='Nicotiana tabacum', wiki='Nicotiana tabacum'),
    't_maize':     dict(gbif='Zea mays', wiki='Maize'),
    't_potato':    dict(gbif='Solanum tuberosum', wiki='Potato'),
    't_rice':      dict(gbif='Oryza sativa', wiki='Oryza sativa'),
    't_silkraw':   dict(gbif='Bombyx mori', wiki='Bombyx mori'),
    't_antique':   dict(wiki='Antique', met='Chinese porcelain Ming', must=['ming']),
    't_carpet':    dict(wiki='Persian carpet', met='Safavid carpet', must=['carpet']),
    't_chintz':    dict(wiki='Chintz', met='palampore India cotton', must=['india']),
    't_musk':      dict(gbif='Moschus moschiferus', wiki='Musk'),
    't_frank':     dict(gbif='Boswellia sacra', wiki='Frankincense', whc=1010),   # 유향의 땅
    't_ambergris': dict(gbif='Physeter macrocephalus', obis='Physeter macrocephalus', wiki='Ambergris'),
    't_sandal':    dict(gbif='Santalum album', wiki='Santalum album'),
    't_pearl':     dict(gbif='Pinctada margaritifera', obis='Pinctada margaritifera', wiki='Pearl'),
    't_jade':      dict(wiki='Jade', met='jade carving Chinese', must=['jade']),
    't_rhino':     dict(gbif='Rhinoceros unicornis', wiki='Indian rhinoceros'),
    't_ivory':     dict(gbif='Loxodonta africana', wiki='Ivory trade'),
    't_coral':     dict(gbif='Corallium rubrum', obis='Corallium rubrum', wiki='Precious coral'),
    't_tortoise':  dict(gbif='Eretmochelys imbricata', obis='Eretmochelys imbricata', wiki='Tortoiseshell'),
    't_herbs':     dict(gbif='Panax ginseng', wiki='Panax ginseng'),
}

# ---------------------------------------------------------------- 유물 (relics.js 의 유물 id)
#  실존하는 박물관 소장품이나 실제 출토품으로 바꾼다. met/si 검색어로 공공 영역 소장품을 찾고,
#  찾지 못하면 wiki 제목의 실제 유물(사진·소장처)을 쓴다.
RELIC = {
    'r_pamukkale':   dict(wiki='Hierapolis', met='Hierapolis marble', must=['hierapolis', 'phrygia']),
    'r_canyon':      dict(si='petrified wood Arizona', wiki='Petrified Forest National Park'),
    'r_carnac':      dict(wiki='Jade axe', met='Neolithic axe jadeite', must=['axe']),
    'r_stonehenge':  dict(wiki='Bush Barrow', met='Bronze Age gold Britain', must=['gold']),
    'r_mycenae':     dict(wiki="Nestor's Cup (Mycenae)", met='Mycenaean gold cup', must=['mycenaean']),
    'r_parthenon':   dict(wiki='Elgin Marbles', met='Parthenon frieze', must=['parthenon', 'attic']),
    'r_delphi':      dict(wiki='Serpent Column', met='bronze tripod Greek', must=['tripod']),
    'r_knossos':     dict(wiki='Bull-leaping', met='Minoan bull rhyton', must=['minoan']),
    'r_pyramid':     dict(met='faience tiles Djoser', must=['djoser', 'tile'], wiki='Step Pyramid of Djoser'),
    'r_giza':        dict(wiki='Great Sphinx of Giza', met='Old Kingdom Giza', must=['giza']),
    'r_kings':       dict(met='shabti New Kingdom', must=['shabti']),
    'r_thebes':      dict(met='Karnak relief', must=['karnak', 'thebes']),
    'r_abusimbel':   dict(met='Ramesses II cartouche', must=['ramesses']),
    'r_troy':        dict(wiki="Priam's Treasure", met='Trojan gold earring', must=['troy', 'troad', 'anatolia']),
    'r_ishtar':      dict(met='Babylon lion glazed brick', must=['babylon']),
    'r_babel':       dict(met='brick Nebuchadnezzar', must=['nebuchadnezzar']),
    'r_persepolis':  dict(met='Achaemenid gold rhyton', must=['achaemenid']),
    'r_mohenjo':     dict(met='Harappan stamp seal unicorn', must=['indus', 'harappan']),
    'r_angkor':      dict(met='Angkor apsara', must=['angkor', 'khmer']),
    'r_yungang':     dict(met='Northern Wei Buddha head', must=['northern wei']),
    'r_qinshi':      dict(wiki='Terracotta Army', met='Qin bronze sword', must=['qin', 'sword']),
    'r_qianling':    dict(met='Tang sancai horse', must=['tang']),
    'r_muryeong':    dict(wiki='Gold diadem ornaments of King Muryeong', met='Baekje gold', must=['baekje', 'three kingdoms']),
    'r_bulguksa':    dict(wiki='Mugujeonggwang Great Dharani Sutra'),
    'r_fertile':     dict(met='dotaku bronze bell Yayoi', must=['yayoi', 'dotaku']),
    'r_borobudur':   dict(met='Central Javanese bronze Buddha', must=['java']),
    'r_tula':        dict(met='obsidian mirror Aztec', must=['obsidian', 'mirror']),
    'r_nazca':       dict(met='Nasca hummingbird vessel', must=['nasca']),
    'r_tiwanaku':    dict(met='Tiwanaku gold', must=['tiwanaku']),
    'r_poitiers':    dict(met='antiphonary manuscript leaf', must=['antiphon', 'gradual']),
    'r_montstmichel':dict(met='illuminated manuscript romance French', must=['manuscript']),
    'r_stave':       dict(wiki='Oseberg ship', met='Viking dragon head', must=['viking', 'norse']),
    'r_rusch':       dict(met='Russian icon gilded', must=['russia', 'icon']),
    'r_hagiasophia': dict(met='Byzantine mosaic', must=['byzantine']),
    'r_prester':     dict(wiki='Letter of Prester John', met='Ethiopian manuscript', must=['ethiopia']),
    'r_cappadocia':  dict(met='Byzantine wall painting', must=['byzantine']),
    'r_sepulchre':   dict(met='mother-of-pearl cross Jerusalem', must=['jerusalem', 'bethlehem']),
    'r_petra':       dict(met='Nabataean eggshell ware', must=['nabataean']),
    'r_ur':          dict(met='cuneiform tablet Ur', must=['cuneiform']),
    'r_brendan':     dict(wiki='Navigatio Sancti Brendani'),
    'r_cibola':      dict(si='turquoise necklace Pueblo', met='turquoise necklace Pueblo', must=['turquoise']),
    'r_ark':         dict(wiki='Bitumen', met='bitumen Mesopotamia', must=['bitumen']),
    'r_djenne':      dict(wiki='Timbuktu Manuscripts'),
    'r_zimbabwe':    dict(wiki='Zimbabwe Bird'),
    'r_delhimosque': dict(met='Mughal Quran illuminated', must=['qur', 'koran']),
    'r_tajmahal':    dict(met='pietra dura Mughal box', must=['mughal']),
    'r_qutb':        dict(wiki='Iron pillar of Delhi'),
    'r_madurai':     dict(met='South Indian bronze lamp', must=['lamp']),
    'r_shwedagon':   dict(si='ruby Burma', wiki='Mogok'),
    'r_ayubuddha':   dict(met='Ayutthaya bronze Buddha', must=['ayutthaya', 'thailand']),
    'r_potala':      dict(met='Tibetan Kangyur manuscript gold', must=['tibet']),
    'r_konjiki':     dict(met='Heian gilt bronze phoenix', must=['heian', 'phoenix']),
    'r_pueblo':      dict(si='Chaco black-on-white jar', met='Chaco black-on-white', must=['black-on-white', 'chaco']),
    'r_machupicchu': dict(met='Inca gold disk', must=['inca']),
    'r_sacsay':      dict(met='Inca star mace head', must=['mace']),
    'r_moai':        dict(wiki='Rongorongo', si='rongorongo'),
    'r_mu':          dict(legend=True),
    'r_mu2':         dict(legend=True),
    'r_isfahanmosque': dict(met='Safavid haft rang tile Isfahan', must=['isfahan', 'safavid']),
    'r_alhambra':    dict(met='Nasrid sword', must=['nasrid']),
    'r_ananda':      dict(met='Burmese lacquer box', must=['burma', 'myanmar']),
    'r_beowulf':     dict(wiki='Sutton Hoo helmet'),
    'r_kingjohn':    dict(wiki="King John's treasure", legend=True),
    'r_agamemnon':   dict(wiki='Mask of Agamemnon'),
    'r_tutankh':     dict(wiki="Tutankhamun's meteoric iron dagger"),
    'r_tutankh2':    dict(met='winged scarab pectoral', must=['pectoral', 'scarab']),
    'r_rosetta':     dict(wiki='Rosetta Stone'),
    'r_sargon':      dict(wiki='Bronze Head from Nineveh'),
    'r_urcrown':     dict(met='headdress Ur gold leaves', must=['ur']),
    'r_goldplate':   dict(wiki='Apadana', met='Achaemenid gold plaque', must=['achaemenid']),
    'r_ewer':        dict(met='Sasanian silver ewer', must=['sasanian']),
    'r_shiva':       dict(met='Shiva as Lord of Dance Nataraja', must=['nataraja', 'shiva']),
    'r_goldelephant':dict(wiki='Wat Ratchaburana, Ayutthaya'),
    'r_jadesuit':    dict(wiki='Jade burial suit'),
    'r_bronze':      dict(met='Shang ritual wine vessel gu', must=['shang']),
    'r_cloisonne':   dict(met='cloisonne incense box Ming', must=['cloisonn']),
    'r_seismo':      dict(wiki='Houfeng Didong Yi'),
    'r_glassbowl':   dict(wiki='Shōsōin', met='Sasanian cut glass bowl', must=['cut glass', 'glass']),
    'r_goldseal':    dict(wiki='King of Na gold seal'),
    'r_crystalskull':dict(si='crystal skull', wiki='Crystal skull'),
    'r_eldorado':    dict(wiki='Muisca raft'),
    'r_jademask':    dict(wiki="Pakal's tomb"),
    'r_grail':       dict(met='Antioch Chalice', must=['chalice']),
    'r_stcrown':     dict(wiki='Holy Crown of Hungary'),
    'r_reliquary':   dict(wiki='Shrine of the Three Kings'),
    'r_ifehead':     dict(wiki='Ife Head'),
    'r_rubber':      dict(met='Olmec rubber ball', must=['ball'], wiki='Mesoamerican ballgame'),
    'r_sequoia':     dict(gbif='Sequoiadendron giganteum'),
    'r_breadfruit':  dict(gbif='Artocarpus altilis'),
    'r_lotus':       dict(gbif='Victoria amazonica'),
    'r_papyrus':     dict(met='papyrus Book of the Dead', must=['papyrus']),
    'r_tarantula':   dict(gbif='Theraphosa blondi'),
    'r_llama':       dict(met='Inca llama figurine', must=['llama']),
    'r_moose':       dict(gbif='Alces alces'),
    'r_frigatebird': dict(gbif='Fregata magnificens'),
    'r_tortoise':    dict(gbif='Chelonoidis niger'),
    'r_albatross':   dict(gbif='Diomedea exulans'),
    'r_kangaroo':    dict(gbif='Macropus giganteus'),
    'r_paradise':    dict(gbif='Paradisaea apoda'),
    'r_sable':       dict(gbif='Martes zibellina'),
    'r_tiger':       dict(gbif='Panthera tigris'),
    'r_coelacanth':  dict(si='coelacanth Latimeria', obis='Latimeria chalumnae'),
    'r_komodo':      dict(gbif='Varanus komodoensis'),
    'r_penguin':     dict(gbif='Spheniscus demersus'),
    'r_ostrich':     dict(met='ostrich feather fan', must=['ostrich']),
    'r_hippo':       dict(met='hippopotamus ivory carving', must=['hippopotamus']),
    'r_crocodile':   dict(gbif='Crocodylus niloticus'),
    'r_polarbear':   dict(gbif='Ursus maritimus'),
    'r_yeti':        dict(wiki='Yeti', legend=True),
    'r_roc':         dict(si='Aepyornis egg', gbif='Aepyornis maximus'),
    'r_mokele':      dict(legend=True),
    'r_minotaur':    dict(met='Minoan double axe labrys', must=['axe']),
    'r_troll':       dict(legend=True),
    'r_nessie':      dict(legend=True),
    'r_khoikhoi':    dict(wiki='Ostrich eggshell', si='ostrich eggshell container'),
    'r_padaung':     dict(wiki='Kayan people (Myanmar)'),
    'r_aborigine':   dict(si='boomerang Australia', met='boomerang Aboriginal', must=['boomerang']),
    'r_inuit':       dict(si='Inuit harpoon', met='Inuit harpoon', must=['harpoon']),
    'r_patagon':     dict(si='guanaco robe Tehuelche', wiki='Guanaco'),
    'r_nestorian':   dict(wiki="Xi'an Stele"),
    'r_aztec':       dict(wiki='Aztec feather shield', met='Aztec feather shield', must=['shield']),
    'r_aztec2':      dict(wiki="Moctezuma's headdress"),
    'r_inca':        dict(met='Inca gold maize', must=['maize', 'corn']),
    'excalibur':     dict(wiki='Excalibur', met='medieval sword', must=['sword'], legend=True),
}
